### ISSUE TITLE
I'm using gcc version 7

### ISSUE THREAD

**Issue by J-M-Ochoada** [EliLillyCo/LillyMol#1]
Is it possible to compile the code using RH devtools 7 series?  Any help would be appreciated!

Thanks!

**Comment by G-Huang** [comment]
We are working on the new release. It shall support both RH7 and OSX in our second release
Thanks
-Gordon

**Comment by J-M-Ochoada** [comment]
Hi Gordon!  Thanks so much for the response.  What's the time frame?  I'm wondering if I should make the effort to go back if it's going to be quite some time.

Jason

**Comment by G-Huang** [comment]
Hi Jason,
  GCC 7 and OSX build have been released. please let us know if you have any question.
-Gordon

**Comment by dhrobertson** [comment]
Gordon,

I was able to compile the MacOS version - apparently fine. However the command line executables do not appear to recognize the command line arguments - tries to interpret them as files. Issue with cmdline modules? 

Any ideas. I will try to debug later this week.

Dan
______________________________________
Daniel H Robertson
dhrobertson@runbox.com

**Comment by G-Huang** [comment]
Hi Dan,
  I will take a look and let you know soon.

Gordon

**Comment by G-Huang** [comment]
Hi Dan
  We have updated the build process and added one shell script to simplify the build for OSX.  Please try it and let us know if it fix the issue you have.

Kind Regards,
Gordon
