### ISSUE TITLE
Does not build on Ubuntu

### ISSUE THREAD

**Issue by MichaelDevine** [EliLillyCo/LillyMol#13]
There are numerous build issues on Ubuntu. 

Please install an unadulterated Ubuntu 18.04, add build_essentials, and follow the build instructions and fix the issues. Multiple minor issues.

Also, the build approach is rather archaic. Please consider updating to something like CMake, which would take care of generating valid makefiles and/or build files for any Linux, OSX, and Windows?

**Comment by G-Huang** [comment]
We will stick on our current build process at this moment. We will let you know if we change our build process in the future.
