### ISSUE TITLE
Illegal Instruction error

### ISSUE THREAD

**Issue by gldurst** [EliLillyCo/LillyMol#14]
I am running into the "Illegal Instruction" error again after compiling LillyMol v3 with gcc-7 then running several of the programs. I saw this before when I compiled v2 with gcc-6 and posted back in Nov 2018. The executables produced all ran to show the help menus, but several (not all) just run and give the  "Illegal Instruction" error and quit, nothing else. I was later able to fix the problem by re-compiling v2 with gcc-7.  Is gcc-8 now required? I'm not sure my Linux Mint 18.3 version is compatible with gcc-8. It's weird that the program seems to run and shows you the help menus, but if you give real arguments to actually do a run it just gives that error and silently dies. There are no other messages. What 's up with this? Some programs run fine without the error but others just die quietly with the Illegal error. I can't diagnose without more info.
I can send example files that give the error if that would help. BTW if I run these same files on another linux box it gives the expected results output.
Thanks for any help in figuring this out.
Greg

**Comment by gldurst** [comment]
More details...
Compiled LillyMol with gcc 7.4.0, seems to go fine
captured stdout and stderror to files
No occurance of ERROR (neither upper/lower case) in stderr or stdout
Some occurances of WARNING but all associated with "declared with attribute warn_unused_result" (seems benign)

**Comment by G-Huang** [comment]
Hi Greg,
  Thank you for the update. We have tested our build using gcc 7.2 under redhat 7.6. We are not surprised to know it does not build using gcc 7 because we have not tested it using other version yet.

-Gordon
