### ISSUE TITLE
LillyMol v4 compiling issues

### ISSUE THREAD

**Issue by gldurst** [EliLillyCo/LillyMol#16]
Hello,
I have attempted to compile the new vers 4 of LillyMol, however none of my compiler choices work. I have gcc/g++ 7.4.0 and gcc/g++ 8.3.0. I cannot get a copy of gcc 7.2.1 (only 7.4.0) for my distribution, (Linuxmint 18.3 /Ubuntu 16.04. Is there something in the RedHat gcc 7.2.1 that is not included in other gcc 7 distributions?

Both gcc 7.4.0 and 8.3.0 appear to compile all binaries and they return the help menu when run, BUT when given real input to process many binaries return "Illegal Instruction" and die. Furthermore some binaries work fine and give good results. 

I also discovered an issue... the compiled binaries in ~LillyMol-master/src/Molecule_Tools/Linuc-gcc-x.x.x are not copied after compilation and I have to copy them manually to the proper bin dir. Something seems to be wrong with the makeall.sh script and associated Makefiles. Please advise.
Thanks,
Greg

**Comment by dxyzx0** [comment]
Try with my compiled version: https://github.com/DingXiangYuanZhiXing/LillyMol
You need docker to run.

**Comment by xuyan-ru** [comment]
Closed as outdated.
