### ISSUE TITLE
molecular_transformation issue with secondary sidechains

### ISSUE THREAD

**Issue by dmoccia** [EliLillyCo/LillyMol#19]
I am running into an issue with running molecular transformations on using my config file.  

I issue the following command...

`molecular_transformations -N 1000 -S my_output -m RMX -z i -M RMX -Z -W rxsep='>>' -W rgsep='+' -A D -u -T 20201104.config`

The relevant portion of my config file is:

`START: [13CH3]OCCN core
AND:
/LillyMol/contrib/data/rxndef/4.2.2_1,2,4-Oxadiazole_synthesis_FROM_amines_aliphatic_primary_AND_carboxylic_acids.rxn||file=input_smiles.smi`

This reaction is defined as 

`(0 Reaction
  (A C Comment "4.2.2_1,2,4-Oxadiazole_synthesis_FROM_amines_aliphatic_primary_AND_carboxylic_acids")
  (0 Scaffold
     (A C smarts "[ND1H2]-[CX4]")
  )
  (1 Sidechain
     (A C smarts "[C](=O)([OH])") 
     (A I remove_atom 1)
  )
  (2 Sidechain
     (A C smiles "C=NN C=NN")
     (A C smarts "C=NN") 
     (A I join (0 0))
     (A C join "1.2 0")
     (A C join "1.0 2 2")
  )
)`

I suspect the "smiles" in the 2 sidechain portion of the rxn definition infers that the following quoted smiles are inserted into the reactants?

I get the following output error:

`iwstring_data_source::_read_more_data_into_read_buffer:unterminated record
iwstring_data_source::_read_more_data_into_read_buffer:unterminated record
iwstring_data_source::_read_more_data_into_read_buffer:unterminated record
Sidechain_Reaction_Site::construct_from_msi_object: no joins specified
Sidechain_Reaction_Site::construct_from_msi_object: no joins specified
Sidechain_Reaction_Site::construct_from_msi_object: no joins specified
Set_of_Reactions::prepOneSideChain:number of sidechains in rxn does not match directive from config file 
Set_of_Reactions::_build:cannot process control file record '/LillyMol/contrib/data/rxndef/4.2.2_1,2,4-Oxadiazole_synthesis_FROM_amines_aliphatic_primary_AND_carboxylic_acids.rxn||file=input_smiles.smi'
No reaction schemes fetched from input`

Of particular note:

`Set_of_Reactions::prepOneSideChain:number of sidechains in rxn does not match directive from config file 
`

It seems as though there is an issue with passing the second sidechain?  I can run molecular_transforms without a second sidechain without issue.  I saw this same error occur using the 9.7.8_Amino_to_guanidino_FROM_amines_aliphatic_AND_amines_aliphatic.rxn reaction as well?

Any help you can provide would be appreciated.

Dennis

**Comment by ChristosN** [comment]
A number of special reactions require the addition of the symbol '||' in the cofig format. These reactions are:
  X.X.X_Aminothiazole_synthesis_FROM_amines_aliphatic_primary_AND_a_h_ketones.rxn
  X.X.X_Aminothiazole_synthesis_FROM_amines_aliphatic_primary_AND_ketones_a_bromo
  9.7.8_Amino_to_guanidino_FROM_amines_aliphatic_AND_amines_aliphatic.rxn
  4.2.2_1,2,4-Oxadiazole_synthesis_FROM_amines_aliphatic_primary_AND_carboxylic_acids.rxn
  4.2.17_1,3-Benzoxazole_synthesis_FROM_amines_aliphatic_primary_AND_o_amino_phenols.rxn

Example of special reactions use in a config file:

# Start enumeration instructions
# Design scope 2382.INT
# Design number of cycles 3
START: [13CH3]OCCN core
AND:
/data/rxndef/4.2.2_1,2,4-Oxadiazole_synthesis_FROM_amines_aliphatic_primary_AND_carboxylic_acids.rxn||file=2382.INTERNAL_C1.int.smi||
|
AND:
/data/rxndef/6.1.6_N-Fmoc_deprotection_FROM_fmoc_AND_Null.rxn
|
AND:
/data/rxndef/9.7.8_Amino_to_guanidino_FROM_amines_aliphatic_AND_amines_aliphatic.rxn||file=2382.INTERNAL_C2.int.smi||
|
AND:
/data/rxndef/9.7.61_Ester_hydrolysis_FROM_esters_methyl_ethyl_AND_Null.rxn
|
AND:
/data/rxndef/2.1.2_Carboxylic_acid_+_amine_condensation_FROM_carboxylic_acids_AND_amines.rxn||file=2382.INTERNAL_C3.int.smi
|
AND:
/data/rxndef/6.1.1_N-Boc_deprotection_FROM_boc_AND_Null.rxn
NOOP
|
AND:
/data/rxndef/6.1.6_N-Fmoc_deprotection_FROM_fmoc_AND_Null.rxn
NOOP
|
AND:
/data/rxndef/9.7.61_Ester_hydrolysis_FROM_esters_methyl_ethyl_AND_Null.rxn
NOOP
# End enumeration instructions
 
 Note the ‘||’ at the end of the line with the reactions 4.2.2 and 9.7.8
