### ISSUE TITLE
Compile error on Mac

### ISSUE THREAD

**Issue by gldurst** [EliLillyCo/LillyMol#20]
Hello,
I am trying to compile LillyMol on a Mac running Mojave OSX. I have zlib and eigen3 installed and have adjusted the makefile.public.OSX file to point to my version of gcc-10 and defined ZLIB, ZLIB_INC and EIGEN_INC. When I run makeall_osx.sh I hit a fatal error compiling tshadow...

g++-10 -c -o OSX-gcc-10/tshadow.o tshadow.cc -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_LFS64_LARGEFILE -D__off_t=off_t -std=c++11 -msse -mfpmath=sse -march=nehalem  -DNDEBUG -DUNIX -mtune=haswell -O2   -I . -I /usr/local/LillyMol-master/include -I /usr/local/LillyMol-master/include/mol -I /usr/local/opt/zlib/include /Users/durst/local/include/eigen-3.3.8
tshadow.cc:16:10: fatal error: Eigen/Dense: No such file or directory
   16 | #include "Eigen/Dense"
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [OSX-gcc-10/tshadow.o] Error 1

So... EIGEN_INC= /Users/durst/local/include/eigen-3.3.8
and tshadow.cc is looking for "Eigen/Dense"       (Eigen is a dir and Dense is a file)

I can combine EIGEN_INC and EIGEN/Dense at the cmd line and 'cat' it to the screen...
cat /Users/durst/local/include/eigen-3.3.8/EIGEN/Dense
#include "Core"
#include "LU"
#include "Cholesky"
#include "QR"
#include "SVD"
#include "Geometry"
#include "Eigenvalues"

Why can't the compiler find this?
Thanks for any help.
Greg

**Comment by gldurst** [comment]
I'm wondering if there is a problem with the path, can you give me an example of EIGEN_INC that you use? Also these are all headers, no compiling required, correct?

**Comment by gldurst** [comment]
Received tip from Ian to hard code the path to the required Eigen headers in the tshadow.cc file. It's the only code requiring Eigen as far as I can tell. This worked fine. Need to add the full path for /blah/blah2/Eigen/Dense and /blah/blah2/Eigen/Core

Someone needs to look into the current makefiles... to fix this

**Comment by xuyan-ru** [comment]
Hi Greg, we have updated the LillyMol to the latest 7.2, also with docker image available, hope starting in this version the build process is more user-friendly!
