### ISSUE TITLE
gfp_make.sh - where is it?

### ISSUE THREAD

**Issue by FreddieM007** [EliLillyCo/LillyMol#21]
All of the gfp tools require .gfp files as input. How can .gfp files be created with the tools available in LillyMol? There used to be gfp_make.sh but it is not part of the repo... Or, is there a hidden option in another tool (e.g. fileconv) that I have overlooked?
Dirk

**Comment by ChristosN** [comment]
gfp_make is a general wrapper around several tools that calculate descriptors. Several of those tools are LillyMol. See LillyMol wiki, for example https://github.com/EliLillyCo/LillyMol/wiki/Instruction#54-iwfp

**Comment by xuyan-ru** [comment]
Hi Dirk, gfp_make.pl is now included under contrib/bin, see https://github.com/EliLillyCo/LillyMol/blob/master/contrib/bin/gfp_make.pl
