### ISSUE TITLE
.rxn file format documentation

### ISSUE THREAD

**Issue by kheyer** [EliLillyCo/LillyMol#22]
Hello,
Are there any documentation sources on the .rxn file format used to represent reactions?

**Comment by cnicolaou** [comment]
Unfortunately not much. You should be able to figure a good bit about it by looking at the numerous examples at https://github.com/EliLillyCo/LillyMol/tree/master/contrib/data/rxndef Feel free to post questions if something is not clear.

**Comment by xuyan-ru** [comment]
Thanks for your inquiry about the reaction file documentation. Unfortunately, this file format was never properly documented, although as pointed out, there are a great many examples available.
 
LillyMol version 7+ implements reactions via Protocol Buffer text_format specifications. The previous format is still supported, but will not be enhanced.
 
Using Protcol Buffers offers many advantages, and leverages the rich support infrastructure available. We have begun documenting this at https://github.com/EliLillyCo/LillyMol/blob/master/docs/Molecule_Tools/trxn.md
Although more work remains to be done – we need to provide more examples of common reactions.
 
One of the advantages of a Protocol Buffer is that it is built on an exact specification of the proto
 
https://github.com/EliLillyCo/LillyMol/blob/master/src/Molecule_Lib/reaction.proto
 
which provides an unambiguous description of what can be in a reaction. Proto definition files also contain descriptions of what the messages and fields are for.
 
This has also enabled building C++ unit tests based on these proto specification. In the unit tester for reactions
https://github.com/EliLillyCo/LillyMol/blob/master/src/Molecule_Lib/reaction_test.cc
you will find many examples of trivial reactions in this format which are used to ensure things are working correctly.
 
This transition to protocol buffer input preserved as much of the existing concepts as possible, so those who had worked with the old style reactions can usually transition fairly quickly.
 
You will find that trxn can be very fast enumerating reactions, which can make a significant difference when dealing with large enumerations.
