### ISSUE TITLE
Tools missing

### ISSUE THREAD

**Issue by FreddieM007** [EliLillyCo/LillyMol#34]
I tried to install the latest version on a new computer (Ubuntu). Overall, it appears to have compiled most tools correctly. However:

1) f2c seems to fail:
ERROR: /home/dirk/.cache/bazel/_bazel_dirk/a46577f26e2aa5baffaaf6e98f70b687/external/local_f2c/BUILD.bazel:2:11: Middleman _middlemen/@local_Uf2c_S_S_Cf2c-cc_library-compile failed: missing input file '@local_f2c//:f2c.h'

2) Also, there are many tool missing where the source code exists but the cli tool is not compiled, e.g.,
fileconv, smiles_mutation, random_molecular_permutations etc.

Please advise.

**Comment by xuyan-ru** [comment]
Hi Freddie, 

Thanks for reaching out and reporting this issue! 

To your first issue, f2c should be included in the build_3rdparty part, can you check if this library is successfully downloaded to the correct location? 

To your second issue, you made a good point, smiles_mutation and random_molecular_permutations do rely on a config/library that are not included in repo, but fileconv should work as is after compiled as the executable. We will be including these config/library files into the repo in the coming release in the next few weeks, stay tuned!

**Comment by xuyan-ru** [comment]
Hi @FreddieM007, we have released the LillyMol v7.4, please take a look at the latest release and see if the missing tools are back. I will close this issue for now, but feel free to let us know if it's not working, happy to reopen and fix!
