### ISSUE TITLE
Issues with iwdemerit

### ISSUE THREAD

**Issue by jmoch** [EliLillyCo/LillyMol#5]
Confused a bit with the requirements for -q.  My full path for the query location is:
/home/jochoada/LillyMol-master/example/iwdemerit/PAINS which contain the query files and queries_latest.

Running with an explicit query file as below does not give any errors:

iwdemerit -A D -A I -S foo -G - -f 99999 -t -W imp2exp -W maxe=1 -E autocreate -q /home/jochoada/LillyMol-master/example/iwdemerit/PAINS/imidazole_A.qry -O hard -W dnv=0 -W slist -i smi /home/jochoada/LillyMol-master/example/iwdemerit/pubchem_example.smi

but the output in foo.demerit isn't correct

[jochoada@svldresource01 SJC]$ more foo.demerit
$SMI<ClC1=C(N2C([H])([H])C([H])([H])OC([H])([H])C2([H])[H])C(=C([H])C(=C1[H])N([H])C([H])([H])C1=C([H])C(=C(OC([H])([H])C(=C([H])[H])[H])C(=C1[H])[H])[H])[H]>
PCN<PBCHM2214928>
|
$SMI<ClC1=C([H])C(=C(N=C2SC(=C(N2N=C([H])C2=C([H])C(=C(C([H])([H])[H])S2)[H])C2=C([H])C(=C(N(=O)=O)C(=C2[H])[H])[H])[H])C(=C1[H])[H])[H]>
PCN<PBCHM2385700>

Running using 
/home/jochoada/LillyMol-master/example/iwdemerit/PAINS/
/home/jochoada/LillyMol-master/example/iwdemerit/PAINS/queries_latest

gives cannot open errors

Running using 
/home/jochoada/LillyMol-master/example/iwdemerit/PAINS/*.qry

gives cannot parse query smiles errors.

Any ideas on what I'm doing incorrectly?

Thanks,
Jason

**Comment by G-Huang** [comment]
We will investigate this issue

**Comment by jmoch** [comment]
I learned a couple of details which helped a lot!  Thank you!

-qF: is needed and essentially it is the full path to the file which contains the list of queries.  In my case the correct syntax was  -qF:/home/jochoada/LillyMol-master/example/iwdemerit/PAINS/queries_latest
For the example it was -qF:queries_latest apparently because he was running the command in the directory where the queries were.

Second I learned that the script outputs the table to std out not to foo.demerits so you can just put > output and get the table that you want out.

This certainly helped me hope it helps others!  Consider the issue I posted closed

Thanks,
Jason
