### ISSUE TITLE
Possible to contribute to Wiki?

### ISSUE THREAD

**Issue by jmoch** [EliLillyCo/LillyMol#6]
As I learn things about the programs which are not detailed in the -help or wiki is it possible to contribute to the wiki?

Thanks,
Jason

**Comment by G-Huang** [comment]
We are in the process of looking into this

**Comment by G-Huang** [comment]
As far as I know, there is no simple way to track the wiki using Github. You can try to send us your updated wiki. We will review and merge them accordingly. 
-Gordon
