### ISSUE TITLE
Illegal instruction error Linux

### ISSUE THREAD

**Issue by gldurst** [EliLillyCo/LillyMol#7]
Just pulled down LillyMol 2.0 and compiled on Linux with no problems. When I try running the molecular_scaffold utility with the provided Pubchem example set I get results but also get the error message: "Illegal instruction". When I try other smiles files I just get the "Illegal instruction" error and no results. Other utilties work fine, (eg. trxn, fetch_smiles_quick, concat_files, msort). What does this error mean or indicate?
Thanks,
Greg

**Comment by G-Huang** [comment]
Hi Greg,
  Could you please send me your command and result for molecular_scaffold. I will check if I can reproduce it here. Thanks

Kind Regards,
Gordon
