### ISSUE TITLE
Issue with command line switches on Mac -- post release of binaries

### ISSUE THREAD

**Issue by dhrobertson** [EliLillyCo/LillyMol#8]
We have made a couple attempts at compiling on the Mac -- it appears to compile fine, but then the commandline arguments are not processed properly. They are not pulled from the args list and are treated as the files -- which throws error.

Bottom-line: For someone who has the Mac version compiled and working correctly, can you zip these files and post it as a release. That way the Mac users can just download the binaries and deploy them in the correct place. It would save many of us lots of time.

**Comment by G-Huang** [comment]
Which version of the LillyMol repo did you download? This is an known issue for older version LillyMol code.
-Gordon
