### ISSUE TITLE
GCC 8.2.1 compatibility

### ISSUE THREAD

**Issue by baerbock** [EliLillyCo/LillyMol#9]
What is blocking the compilation with GCC 8.2.1 ?

**Comment by G-Huang** [comment]
Hi,
  We only verified the build process using gcc 7.2.1 under linux. However, I think you should be able to build using 8.2.1 with modification on the makefile.

Kind Regards,
Gordon

**Comment by dxyzx0** [comment]
@baerbock  Try with my compiled version: https://github.com/DingXiangYuanZhiXing/LillyMol
You need docker to run.

**Comment by xuyan-ru** [comment]
Closed as outdated, please check the latest 7.0+ release of LillyMol that support GCC compiler from 10 to 13, docker image is also available starting in this release (7.2+).
